spring:
    application:
            name: retail-sku
    datasource:
        url: jdbc:mysql://localhost:3306/retail_sku
        username: root
        password: 123456
server:
  port: 10001

flyway:
  locations: classpath:db/migration

---
spring:
  profiles: sit
  datasource:
      url: jdbc:mysql://10.207.11.202:3306/retail_sku
      username: retail
      password: retail__123