spring:
    application:
      name: retail-gateway

server:
  port: 11000

zuul:
  routes:
    retail-stock:
      path: /api/stocks/**
      serviceId: retail-stock


eureka:
      instance:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
