spring:
    application:
      name: retail-gateway
    rabbitmq:
            port: 5672
            host: '10.207.11.202'
            username: guest
            password: guest
            listener:
              max-concurrency: 1
              prefetch: 1
              acknowledge-mode: auto
              auto-startup: true
            dynamic: true

server:
  port: 11000

zuul:
  routes:
    retail-stock:
      path: /api/amount/**
      serviceId: retail-stock


eureka:
      instance:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
