spring:
    application:
            name: retail-stock
    datasource:
        url: jdbc:mysql://10.207.11.202:3306/retail_stock
        username: root
        password: retail__123
server:
  port: 10002

flyway:
  locations: classpath:db/migration

---
spring:
  profiles: sit
  datasource:
      url: jdbc:mysql://54.255.182.198:3306/retail_stock
      username: retail
      password: retail__123