spring:
    application:
            name: ratail-config
    cloud:
      config:
        server:
          git:
            uri: http://10.207.11.201:8000/git/config_service
            searchPaths: config-repo
server:
  port: 8888