spring:
    application:
            name: ratail-config
    cloud:
      config:
        server:
          prefix: /config-repo
          git:
            uri: http://10.207.11.201:8000/git/config_service
server:
  port: 8888